//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library1Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Library1Entities : DbContext
    {
        public Library1Entities()
            : base("name=Library1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Borrow> Borrow { get; set; }
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<ViewBorrow> ViewBorrow { get; set; }
    }
}
