//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library1Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewBorrow
    {
        public int BorrowID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<int> BookID { get; set; }
        public string BorrowDate { get; set; }
        public string ReturnDate { get; set; }
        public string Fine { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Title { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> ISBN { get; set; }
    }
}
